export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_TODOS = 'CREATE_LIST_TODOS';
export const ADD_LIST_TO_VIEW = 'ADD_LIST_TO_VIEW';
export const REMOVE_LIST_FROM_VIEW = 'REMOVE_LIST_FROM_VIEW';
export const UPDATE_LIST_ID = 'UPDATE_LIST_ID';
export const BEGIN_RENAME_LIST = 'BEGIN_RENAME_LIST';
export const END_RENAME_LIST = 'END_RENAME_LIST';
export const SAVE_RENAME_LIST = 'SAVE_RENAME_LIST';
export const TOGGLE_LIST_VIEW = 'TOGGLE_LIST_VIEW';
export const REORDER_LISTS = 'REORDER_LISTS';
export const DELETE_LIST = 'DELETE_LIST';
export const REMOVE_LIST_TODOS = 'REMOVE_LIST_TODOS';

export const CREATE_TODO = 'CREATE_TODO';
export const UPDATE_TODO_ID = 'UPDATE_TODO_ID';
export const MOVE_TODO_TO_LIST = 'MOVE_TODO_TO_LIST';
export const REMOVE_TODO_FROM_LIST = 'REMOVE_TODO_FROM_LIST';
export const BEGIN_EDIT_TODO = 'BEGIN_EDIT_TODO';
export const END_EDIT_TODO = 'END_EDIT_TODO';
export const SAVE_EDIT_TODO = 'SAVE_EDIT_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const REORDER_TODOS = 'REORDER_TODOS';

export const SAVE_STATE = 'SAVE_STATE';
export const LOAD_STATE = 'LOAD_STATE';
export const HYDRATE_STATE = 'HYDRATE_STATE';
